### ISSUE TITLE
Missing main.qml in LockStatev1.0.plasmoid

### ISSUE THREAD

**Issue by yullaw** [jasonmoofang/LockState#2]
Hi Jasonmoofang,

on the web page https://store.kde.org/p/1175153/ you provide LockStatev1.0.plasmoid, where is not ../contents/ui/main.qml included.

Compare it with your master LockState-master/contents/ui/main.qml

Without main.qml file the widget can't be installed on the desktop/panel in Plasma 5.

Thanks!

**Comment by jasonmoofang** [comment]
That is very strange. I have removed and reuploaded the plasmoid file on the store. Thanks for reporting!
